(defun darrer (l)
    (print l)
    (cond ( (null (cdr l)) (car l) )
          ( t (darrer (cdr l)))  ))

(defun long (l)
    (cond ( (null l) 0)
          ( t (+ 1 ( long (cdr l)))) ))

(defun pertany (x l)
    (cond ( (null l) nil )
          ( (equal (car l) x) t)
          ( t (pertany x (cdr l)))  
          ))

(defun exp (b e)
    (cond ( (= e 0) 1)
          ( (plusp e) (* b (exp b (- e 1))))
          ))

(defun fib (n)
    (cond ( (= n 0) 0)
          ( (= n 1) 1) 
          ( t (+ (fib (- n 1)) (fib (- n 2))))
          ))

(defun dividir (m n)
    (cond ( (< m n) 0) 
          ( t (+ 1 (dividir (- m n) n))) 
          ))

(defun esborra (x l)
    (cond ( (null l) '())
          ( (equal x (car l)) (cdr l))
          ( t (cons (car l) (esborra x (cdr l))))
          ))  

(defun esborra-tot (x l)
    (cond ( (null l) '())
          ( (equal x (car l)) (esborra-tot x (cdr l)))
          ( t (cons (car l) (esborra-tot x (cdr l))))
          ))  

(defun esborra-n (x n l)
    (cond ( (null l) '())
          ( (equal n 0) l)
          ( (equal x (car l)) (esborra-n x (- n 1) (cdr l)))
          ( t (cons (car l) (esborra-n x n (cdr l))))
          ))  