(defun aplana (l)
    (cond ( (null l) l)
          ( (atom (car l))
            (cons (car l) (aplana(cdr l))))
          (t (append (aplana (car l)) (aplana (cdr l))))
          ))

(defun treuprimers (n l)
    (cond ((= n 0) l)
          (t (treuprimers (- n 1) (cdr l)))
          ))

(defun tornaprimers (n l)
    (cond ((null l) nil) 
          ((= n 0) nil)
          (t (cons (car l) (tornaprimers (- n 1) (cdr l))))
          ))

(defun insereix (x n l)
    (cond ( (= n 1) (cons x l))
          (t (cons (car l) (insereix x (- n 1) (cdr l))))
          ))

(defun canvia 3 (n l e)
    (cond ((= n 1) (cons per (cdr l)))
          (t (cons (car l) (canvia (- n 1) (cdr l) per)))
          ))

(defun insereix_esquerra (y x l)
    (cond ((null l) nil)
          ((equal (car l) y) (cons x l))
          (t (cons (car l) (insereix_esquerra y x (cdr l))))
          ))

(defun insereix-dreta (dequi que l)
    (cond ((null l) nil)
          ((equal (car l) dequi) (cons (car l) (cons que (cdr l))))
          (t (cons (car l) (insereix-dreta dequi que (cdr l))))
          ))

(defun eget (clau l)
    (cond ((null l) nil)
          ( (eq (car l) clau) (cadr l))
          (t (eget clau (cddr l)))
          ))

(defun econs (cl v l)
    (cond ()
          ))

(defun erem (clau l)
    (cond ((null l) nil)
          ((eq (car l) clau) cddr l)
          (t (cons (car l) (cons (cadr l) (erem (clau (cddr l))))))
          ))

(defun eset (clau valor l)
    (cond ((null l) (list clau valor))
          ((eq (car l) clau (cons (car l) (cons valor (cddr l)))))
          (t (cons (car l) (cons (cadr l) (eset (clau valor (cddr l))))))
          ))